name: prisma_dart
version: 6.3.1
description:
repository: 
environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  json_annotation: 
  recase: ^4.0.0

dev_dependencies:
    json_serializable: ^6.3.1
    build_runner:
    lints: ^2.0.0

