name: prisma_dart
version: 6.3.1
description:
repository: 
environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  code_builder: ^4.2.0
  collection: ^1.16.0
  dart_style: ^2.2.3
  http: ^0.13.4
  json_annotation: 
  path: ^1.8.2
  recase: ^4.0.0

dev_dependencies:
    json_serializable: ^6.3.1
    build_runner:
    lints: ^2.0.0

