import 'dart:io';

import 'package:path/path.dart';
import 'package:prisma_dart/src/generator/generator.dart';

runGenerator(Root input) {
  if (input.generator.config.disableGitignore != "true" &&
      input.generator.config.disableGoBinaries != "true") {
    print("writing gitignore file");
    var gitignore = "# gitignore generated by Prisma Client Go. DO NOT EDIT.";
    final dir = Directory(input.generator.output.value)
      ..createSync(recursive: true);
    File(
      join(dir.path, ".gitignore"),
    ).writeAsStringSync(gitignore);
  }
}
