// Code generated by Prisma Client Go. DO NOT EDIT.
//nolint
// +build !codeanalysis
// +build linux
// +build !prisma_ignore
// +build !debian_openssl_1_0_x
// +build !debian_openssl_1_1_x
// +build !rhel_openssl_1_0_x
// +build !rhel_openssl_1_1_x


import 'package:prisma_dart/src/binaries/unpack/unpack.dart';


void init() {
	copyEngineToUnpackTmp("/home/aliammar/Desktop/dart_build_learn/prisma-client-dart/example/lib/prisma/engine/linux", "linux", "efdf9b1183dddfd4258cd181a72125755215ab7b");
}
